#!/bin/bash

#JAVA="/usr/lib/jvm/java-1.6.0-sun-1.6.0/bin/"
JAVA=""
#/usr/lib/jvm/java-1.6.0-openjdk-1.6.0/bin/"
XSD="Powerlink_Main.xsd"

[ ! -d src ] && mkdir src 
[ ! -d build ] && mkdir build
[ ! -f $XSD ] && { echo "File $XSD does not exist."; exit 1; }

${JAVA}xjc $XSD -d src/
${JAVA}javac src/org/ethernet_powerlink/* -classpath src/org/ethernet_powerlink/ -d build/
${JAVA}jar -cf powerlink.jar -C build/ .
${JAVA}javadoc -sourcepath src -d doc org.ethernet_powerlink
 
