//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}dataTypeList" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}functionTypeList" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}functionInstanceList" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}templateList" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}parameterList"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}parameterGroupList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "dataTypeList",
    "functionTypeList",
    "functionInstanceList",
    "templateList",
    "parameterList",
    "parameterGroupList"
})
@XmlRootElement(name = "ApplicationProcess")
public class ApplicationProcess {

    protected DataTypeList dataTypeList;
    protected FunctionTypeList functionTypeList;
    protected FunctionInstanceList functionInstanceList;
    protected TemplateList templateList;
    @XmlElement(required = true)
    protected ParameterList parameterList;
    protected ParameterGroupList parameterGroupList;

    /**
     * Gets the value of the dataTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link DataTypeList }
     *     
     */
    public DataTypeList getDataTypeList() {
        return dataTypeList;
    }

    /**
     * Sets the value of the dataTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataTypeList }
     *     
     */
    public void setDataTypeList(DataTypeList value) {
        this.dataTypeList = value;
    }

    /**
     * Gets the value of the functionTypeList property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionTypeList }
     *     
     */
    public FunctionTypeList getFunctionTypeList() {
        return functionTypeList;
    }

    /**
     * Sets the value of the functionTypeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionTypeList }
     *     
     */
    public void setFunctionTypeList(FunctionTypeList value) {
        this.functionTypeList = value;
    }

    /**
     * Gets the value of the functionInstanceList property.
     * 
     * @return
     *     possible object is
     *     {@link FunctionInstanceList }
     *     
     */
    public FunctionInstanceList getFunctionInstanceList() {
        return functionInstanceList;
    }

    /**
     * Sets the value of the functionInstanceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link FunctionInstanceList }
     *     
     */
    public void setFunctionInstanceList(FunctionInstanceList value) {
        this.functionInstanceList = value;
    }

    /**
     * Gets the value of the templateList property.
     * 
     * @return
     *     possible object is
     *     {@link TemplateList }
     *     
     */
    public TemplateList getTemplateList() {
        return templateList;
    }

    /**
     * Sets the value of the templateList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TemplateList }
     *     
     */
    public void setTemplateList(TemplateList value) {
        this.templateList = value;
    }

    /**
     * Gets the value of the parameterList property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterList }
     *     
     */
    public ParameterList getParameterList() {
        return parameterList;
    }

    /**
     * Sets the value of the parameterList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterList }
     *     
     */
    public void setParameterList(ParameterList value) {
        this.parameterList = value;
    }

    /**
     * Gets the value of the parameterGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterGroupList }
     *     
     */
    public ParameterGroupList getParameterGroupList() {
        return parameterGroupList;
    }

    /**
     * Sets the value of the parameterGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterGroupList }
     *     
     */
    public void setParameterGroupList(ParameterGroupList value) {
        this.parameterGroupList = value;
    }

}
