//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}characteristicsList" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}standardComplianceList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "characteristicsList",
    "standardComplianceList"
})
@XmlRootElement(name = "capabilities")
public class Capabilities {

    @XmlElement(required = true)
    protected List<CharacteristicsList> characteristicsList;
    protected StandardComplianceList standardComplianceList;

    /**
     * Gets the value of the characteristicsList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the characteristicsList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCharacteristicsList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CharacteristicsList }
     * 
     * 
     */
    public List<CharacteristicsList> getCharacteristicsList() {
        if (characteristicsList == null) {
            characteristicsList = new ArrayList<CharacteristicsList>();
        }
        return this.characteristicsList;
    }

    /**
     * Gets the value of the standardComplianceList property.
     * 
     * @return
     *     possible object is
     *     {@link StandardComplianceList }
     *     
     */
    public StandardComplianceList getStandardComplianceList() {
        return standardComplianceList;
    }

    /**
     * Sets the value of the standardComplianceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link StandardComplianceList }
     *     
     */
    public void setStandardComplianceList(StandardComplianceList value) {
        this.standardComplianceList = value;
    }

}
