//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}vendorName"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}vendorID" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}vendorText" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}deviceFamily" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}productFamily" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}productName"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}productID" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}productText" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}orderNumber" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}version" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}buildDate" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}specificationRevision" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}instanceName" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "vendorName",
    "vendorID",
    "vendorText",
    "deviceFamily",
    "productFamily",
    "productName",
    "productID",
    "productText",
    "orderNumber",
    "version",
    "buildDate",
    "specificationRevision",
    "instanceName"
})
@XmlRootElement(name = "DeviceIdentity")
public class DeviceIdentity {

    @XmlElement(required = true)
    protected VendorName vendorName;
    protected VendorID vendorID;
    protected VendorText vendorText;
    protected DeviceFamily deviceFamily;
    protected ProductFamily productFamily;
    @XmlElement(required = true)
    protected ProductName productName;
    protected ProductID productID;
    protected ProductText productText;
    protected List<OrderNumber> orderNumber;
    protected List<Version> version;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar buildDate;
    protected SpecificationRevision specificationRevision;
    protected InstanceName instanceName;

    /**
     * Gets the value of the vendorName property.
     * 
     * @return
     *     possible object is
     *     {@link VendorName }
     *     
     */
    public VendorName getVendorName() {
        return vendorName;
    }

    /**
     * Sets the value of the vendorName property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorName }
     *     
     */
    public void setVendorName(VendorName value) {
        this.vendorName = value;
    }

    /**
     * Gets the value of the vendorID property.
     * 
     * @return
     *     possible object is
     *     {@link VendorID }
     *     
     */
    public VendorID getVendorID() {
        return vendorID;
    }

    /**
     * Sets the value of the vendorID property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorID }
     *     
     */
    public void setVendorID(VendorID value) {
        this.vendorID = value;
    }

    /**
     * Gets the value of the vendorText property.
     * 
     * @return
     *     possible object is
     *     {@link VendorText }
     *     
     */
    public VendorText getVendorText() {
        return vendorText;
    }

    /**
     * Sets the value of the vendorText property.
     * 
     * @param value
     *     allowed object is
     *     {@link VendorText }
     *     
     */
    public void setVendorText(VendorText value) {
        this.vendorText = value;
    }

    /**
     * Gets the value of the deviceFamily property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceFamily }
     *     
     */
    public DeviceFamily getDeviceFamily() {
        return deviceFamily;
    }

    /**
     * Sets the value of the deviceFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceFamily }
     *     
     */
    public void setDeviceFamily(DeviceFamily value) {
        this.deviceFamily = value;
    }

    /**
     * Gets the value of the productFamily property.
     * 
     * @return
     *     possible object is
     *     {@link ProductFamily }
     *     
     */
    public ProductFamily getProductFamily() {
        return productFamily;
    }

    /**
     * Sets the value of the productFamily property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductFamily }
     *     
     */
    public void setProductFamily(ProductFamily value) {
        this.productFamily = value;
    }

    /**
     * Gets the value of the productName property.
     * 
     * @return
     *     possible object is
     *     {@link ProductName }
     *     
     */
    public ProductName getProductName() {
        return productName;
    }

    /**
     * Sets the value of the productName property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductName }
     *     
     */
    public void setProductName(ProductName value) {
        this.productName = value;
    }

    /**
     * Gets the value of the productID property.
     * 
     * @return
     *     possible object is
     *     {@link ProductID }
     *     
     */
    public ProductID getProductID() {
        return productID;
    }

    /**
     * Sets the value of the productID property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductID }
     *     
     */
    public void setProductID(ProductID value) {
        this.productID = value;
    }

    /**
     * Gets the value of the productText property.
     * 
     * @return
     *     possible object is
     *     {@link ProductText }
     *     
     */
    public ProductText getProductText() {
        return productText;
    }

    /**
     * Sets the value of the productText property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductText }
     *     
     */
    public void setProductText(ProductText value) {
        this.productText = value;
    }

    /**
     * Gets the value of the orderNumber property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the orderNumber property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrderNumber().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OrderNumber }
     * 
     * 
     */
    public List<OrderNumber> getOrderNumber() {
        if (orderNumber == null) {
            orderNumber = new ArrayList<OrderNumber>();
        }
        return this.orderNumber;
    }

    /**
     * Gets the value of the version property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the version property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVersion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Version }
     * 
     * 
     */
    public List<Version> getVersion() {
        if (version == null) {
            version = new ArrayList<Version>();
        }
        return this.version;
    }

    /**
     * Gets the value of the buildDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBuildDate() {
        return buildDate;
    }

    /**
     * Sets the value of the buildDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBuildDate(XMLGregorianCalendar value) {
        this.buildDate = value;
    }

    /**
     * Gets the value of the specificationRevision property.
     * 
     * @return
     *     possible object is
     *     {@link SpecificationRevision }
     *     
     */
    public SpecificationRevision getSpecificationRevision() {
        return specificationRevision;
    }

    /**
     * Sets the value of the specificationRevision property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecificationRevision }
     *     
     */
    public void setSpecificationRevision(SpecificationRevision value) {
        this.specificationRevision = value;
    }

    /**
     * Gets the value of the instanceName property.
     * 
     * @return
     *     possible object is
     *     {@link InstanceName }
     *     
     */
    public InstanceName getInstanceName() {
        return instanceName;
    }

    /**
     * Sets the value of the instanceName property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstanceName }
     *     
     */
    public void setInstanceName(InstanceName value) {
        this.instanceName = value;
    }

}
