//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}capabilities"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}picturesList" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}dictionaryList" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "capabilities",
    "picturesList",
    "dictionaryList"
})
@XmlRootElement(name = "DeviceFunction")
public class DeviceFunction {

    @XmlElement(required = true)
    protected Capabilities capabilities;
    protected PicturesList picturesList;
    protected DictionaryList dictionaryList;

    /**
     * Gets the value of the capabilities property.
     * 
     * @return
     *     possible object is
     *     {@link Capabilities }
     *     
     */
    public Capabilities getCapabilities() {
        return capabilities;
    }

    /**
     * Sets the value of the capabilities property.
     * 
     * @param value
     *     allowed object is
     *     {@link Capabilities }
     *     
     */
    public void setCapabilities(Capabilities value) {
        this.capabilities = value;
    }

    /**
     * Gets the value of the picturesList property.
     * 
     * @return
     *     possible object is
     *     {@link PicturesList }
     *     
     */
    public PicturesList getPicturesList() {
        return picturesList;
    }

    /**
     * Sets the value of the picturesList property.
     * 
     * @param value
     *     allowed object is
     *     {@link PicturesList }
     *     
     */
    public void setPicturesList(PicturesList value) {
        this.picturesList = value;
    }

    /**
     * Gets the value of the dictionaryList property.
     * 
     * @return
     *     possible object is
     *     {@link DictionaryList }
     *     
     */
    public DictionaryList getDictionaryList() {
        return dictionaryList;
    }

    /**
     * Sets the value of the dictionaryList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DictionaryList }
     *     
     */
    public void setDictionaryList(DictionaryList value) {
        this.dictionaryList = value;
    }

}
