//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}inputVars" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}outputVars" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}configVars" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inputVars",
    "outputVars",
    "configVars"
})
@XmlRootElement(name = "interfaceList")
public class InterfaceList {

    protected InputVars inputVars;
    protected OutputVars outputVars;
    protected ConfigVars configVars;

    /**
     * Gets the value of the inputVars property.
     * 
     * @return
     *     possible object is
     *     {@link InputVars }
     *     
     */
    public InputVars getInputVars() {
        return inputVars;
    }

    /**
     * Sets the value of the inputVars property.
     * 
     * @param value
     *     allowed object is
     *     {@link InputVars }
     *     
     */
    public void setInputVars(InputVars value) {
        this.inputVars = value;
    }

    /**
     * Gets the value of the outputVars property.
     * 
     * @return
     *     possible object is
     *     {@link OutputVars }
     *     
     */
    public OutputVars getOutputVars() {
        return outputVars;
    }

    /**
     * Sets the value of the outputVars property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutputVars }
     *     
     */
    public void setOutputVars(OutputVars value) {
        this.outputVars = value;
    }

    /**
     * Gets the value of the configVars property.
     * 
     * @return
     *     possible object is
     *     {@link ConfigVars }
     *     
     */
    public ConfigVars getConfigVars() {
        return configVars;
    }

    /**
     * Sets the value of the configVars property.
     * 
     * @param value
     *     allowed object is
     *     {@link ConfigVars }
     *     
     */
    public void setConfigVars(ConfigVars value) {
        this.configVars = value;
    }

}
