//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://www.ethernet-powerlink.org}g_labels"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}LEDstate" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="LEDcolors" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="monocolor"/>
 *             &lt;enumeration value="bicolor"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="LEDtype">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="IO"/>
 *             &lt;enumeration value="device"/>
 *             &lt;enumeration value="communication"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "labelOrDescriptionOrLabelRef",
    "leDstate"
})
@XmlRootElement(name = "LED")
public class LED {

    @XmlElements({
        @XmlElement(name = "descriptionRef", type = org.ethernet_powerlink.Count.DescriptionRef.class),
        @XmlElement(name = "labelRef", type = org.ethernet_powerlink.Count.LabelRef.class),
        @XmlElement(name = "label", type = org.ethernet_powerlink.Count.Label.class),
        @XmlElement(name = "description", type = org.ethernet_powerlink.Count.Description.class)
    })
    protected List<Object> labelOrDescriptionOrLabelRef;
    @XmlElement(name = "LEDstate", required = true)
    protected List<LEDstate> leDstate;
    @XmlAttribute(name = "LEDcolors", required = true)
    protected String leDcolors;
    @XmlAttribute(name = "LEDtype")
    protected String leDtype;

    /**
     * Gets the value of the labelOrDescriptionOrLabelRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the labelOrDescriptionOrLabelRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLabelOrDescriptionOrLabelRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.ethernet_powerlink.Count.DescriptionRef }
     * {@link org.ethernet_powerlink.Count.LabelRef }
     * {@link org.ethernet_powerlink.Count.Label }
     * {@link org.ethernet_powerlink.Count.Description }
     * 
     * 
     */
    public List<Object> getLabelOrDescriptionOrLabelRef() {
        if (labelOrDescriptionOrLabelRef == null) {
            labelOrDescriptionOrLabelRef = new ArrayList<Object>();
        }
        return this.labelOrDescriptionOrLabelRef;
    }

    /**
     * Gets the value of the leDstate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leDstate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLEDstate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LEDstate }
     * 
     * 
     */
    public List<LEDstate> getLEDstate() {
        if (leDstate == null) {
            leDstate = new ArrayList<LEDstate>();
        }
        return this.leDstate;
    }

    /**
     * Gets the value of the leDcolors property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEDcolors() {
        return leDcolors;
    }

    /**
     * Sets the value of the leDcolors property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEDcolors(String value) {
        this.leDcolors = value;
    }

    /**
     * Gets the value of the leDtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLEDtype() {
        return leDtype;
    }

    /**
     * Sets the value of the leDtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLEDtype(String value) {
        this.leDtype = value;
    }

}
