//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.HexBinaryAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Object" maxOccurs="65535">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="SubObject" maxOccurs="255" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;attribute name="subIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *                           &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="objectType" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                           &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *                           &lt;attribute name="lowLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="highLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="accessType">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                 &lt;enumeration value="ro"/>
 *                                 &lt;enumeration value="wo"/>
 *                                 &lt;enumeration value="rw"/>
 *                                 &lt;enumeration value="const"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="actualValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="denotation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="PDOmapping">
 *                             &lt;simpleType>
 *                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                                 &lt;enumeration value="no"/>
 *                                 &lt;enumeration value="default"/>
 *                                 &lt;enumeration value="optional"/>
 *                                 &lt;enumeration value="TPDO"/>
 *                                 &lt;enumeration value="RPDO"/>
 *                                 &lt;enumeration value="true"/>
 *                                 &lt;enumeration value="false"/>
 *                               &lt;/restriction>
 *                             &lt;/simpleType>
 *                           &lt;/attribute>
 *                           &lt;attribute name="objFlags" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *                           &lt;attribute name="uniqueIDRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="objectType" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *                 &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *                 &lt;attribute name="lowLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="highLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="accessType">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="ro"/>
 *                       &lt;enumeration value="wo"/>
 *                       &lt;enumeration value="rw"/>
 *                       &lt;enumeration value="const"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="actualValue" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="denotation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="PDOmapping">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                       &lt;enumeration value="no"/>
 *                       &lt;enumeration value="default"/>
 *                       &lt;enumeration value="optional"/>
 *                       &lt;enumeration value="TPDO"/>
 *                       &lt;enumeration value="RPDO"/>
 *                       &lt;enumeration value="true"/>
 *                       &lt;enumeration value="false"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="objFlags" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
 *                 &lt;attribute name="uniqueIDRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
 *                 &lt;attribute name="subNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="mandatoryObjects" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="optionalObjects" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="manufacturerObjects" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "object"
})
@XmlRootElement(name = "ObjectList")
public class ObjectList {

    @XmlElement(name = "Object", required = true)
    protected List<ObjectList.Object> object;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedInt")
    protected Long mandatoryObjects;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedInt")
    protected Long optionalObjects;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedInt")
    protected Long manufacturerObjects;

    /**
     * Gets the value of the object property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the object property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObject().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ObjectList.Object }
     * 
     * 
     */
    public List<ObjectList.Object> getObject() {
        if (object == null) {
            object = new ArrayList<ObjectList.Object>();
        }
        return this.object;
    }

    /**
     * Gets the value of the mandatoryObjects property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getMandatoryObjects() {
        return mandatoryObjects;
    }

    /**
     * Sets the value of the mandatoryObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setMandatoryObjects(Long value) {
        this.mandatoryObjects = value;
    }

    /**
     * Gets the value of the optionalObjects property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getOptionalObjects() {
        return optionalObjects;
    }

    /**
     * Sets the value of the optionalObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setOptionalObjects(Long value) {
        this.optionalObjects = value;
    }

    /**
     * Gets the value of the manufacturerObjects property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getManufacturerObjects() {
        return manufacturerObjects;
    }

    /**
     * Sets the value of the manufacturerObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setManufacturerObjects(Long value) {
        this.manufacturerObjects = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="SubObject" maxOccurs="255" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;attribute name="subIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
     *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="objectType" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *                 &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
     *                 &lt;attribute name="lowLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="highLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="accessType">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                       &lt;enumeration value="ro"/>
     *                       &lt;enumeration value="wo"/>
     *                       &lt;enumeration value="rw"/>
     *                       &lt;enumeration value="const"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="actualValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="denotation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="PDOmapping">
     *                   &lt;simpleType>
     *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *                       &lt;enumeration value="no"/>
     *                       &lt;enumeration value="default"/>
     *                       &lt;enumeration value="optional"/>
     *                       &lt;enumeration value="TPDO"/>
     *                       &lt;enumeration value="RPDO"/>
     *                       &lt;enumeration value="true"/>
     *                       &lt;enumeration value="false"/>
     *                     &lt;/restriction>
     *                   &lt;/simpleType>
     *                 &lt;/attribute>
     *                 &lt;attribute name="objFlags" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
     *                 &lt;attribute name="uniqueIDRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="index" use="required" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="objectType" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *       &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
     *       &lt;attribute name="lowLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="highLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="accessType">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="ro"/>
     *             &lt;enumeration value="wo"/>
     *             &lt;enumeration value="rw"/>
     *             &lt;enumeration value="const"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="actualValue" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="denotation" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="PDOmapping">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *             &lt;enumeration value="no"/>
     *             &lt;enumeration value="default"/>
     *             &lt;enumeration value="optional"/>
     *             &lt;enumeration value="TPDO"/>
     *             &lt;enumeration value="RPDO"/>
     *             &lt;enumeration value="true"/>
     *             &lt;enumeration value="false"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="objFlags" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
     *       &lt;attribute name="uniqueIDRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
     *       &lt;attribute name="subNumber" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "subObject"
    })
    public static class Object {

        @XmlElement(name = "SubObject")
        protected List<ObjectList.Object.SubObject> subObject;
        @XmlAttribute(required = true)
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] index;
        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute(required = true)
        @XmlSchemaType(name = "unsignedByte")
        protected short objectType;
        @XmlAttribute
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] dataType;
        @XmlAttribute
        protected String lowLimit;
        @XmlAttribute
        protected String highLimit;
        @XmlAttribute
        protected String accessType;
        @XmlAttribute
        protected String defaultValue;
        @XmlAttribute
        protected String actualValue;
        @XmlAttribute
        protected String denotation;
        @XmlAttribute(name = "PDOmapping")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String pdOmapping;
        @XmlAttribute
        @XmlJavaTypeAdapter(HexBinaryAdapter.class)
        @XmlSchemaType(name = "hexBinary")
        protected byte[] objFlags;
        @XmlAttribute
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected java.lang.Object uniqueIDRef;
        @XmlAttribute
        @XmlSchemaType(name = "unsignedByte")
        protected Short subNumber;

        /**
         * Gets the value of the subObject property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the subObject property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSubObject().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ObjectList.Object.SubObject }
         * 
         * 
         */
        public List<ObjectList.Object.SubObject> getSubObject() {
            if (subObject == null) {
                subObject = new ArrayList<ObjectList.Object.SubObject>();
            }
            return this.subObject;
        }

        /**
         * Gets the value of the index property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getIndex() {
            return index;
        }

        /**
         * Sets the value of the index property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIndex(byte[] value) {
            this.index = ((byte[]) value);
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the objectType property.
         * 
         */
        public short getObjectType() {
            return objectType;
        }

        /**
         * Sets the value of the objectType property.
         * 
         */
        public void setObjectType(short value) {
            this.objectType = value;
        }

        /**
         * Gets the value of the dataType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getDataType() {
            return dataType;
        }

        /**
         * Sets the value of the dataType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDataType(byte[] value) {
            this.dataType = ((byte[]) value);
        }

        /**
         * Gets the value of the lowLimit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLowLimit() {
            return lowLimit;
        }

        /**
         * Sets the value of the lowLimit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLowLimit(String value) {
            this.lowLimit = value;
        }

        /**
         * Gets the value of the highLimit property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHighLimit() {
            return highLimit;
        }

        /**
         * Sets the value of the highLimit property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHighLimit(String value) {
            this.highLimit = value;
        }

        /**
         * Gets the value of the accessType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAccessType() {
            return accessType;
        }

        /**
         * Sets the value of the accessType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAccessType(String value) {
            this.accessType = value;
        }

        /**
         * Gets the value of the defaultValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDefaultValue() {
            return defaultValue;
        }

        /**
         * Sets the value of the defaultValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDefaultValue(String value) {
            this.defaultValue = value;
        }

        /**
         * Gets the value of the actualValue property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getActualValue() {
            return actualValue;
        }

        /**
         * Sets the value of the actualValue property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setActualValue(String value) {
            this.actualValue = value;
        }

        /**
         * Gets the value of the denotation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDenotation() {
            return denotation;
        }

        /**
         * Sets the value of the denotation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDenotation(String value) {
            this.denotation = value;
        }

        /**
         * Gets the value of the pdOmapping property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPDOmapping() {
            return pdOmapping;
        }

        /**
         * Sets the value of the pdOmapping property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPDOmapping(String value) {
            this.pdOmapping = value;
        }

        /**
         * Gets the value of the objFlags property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public byte[] getObjFlags() {
            return objFlags;
        }

        /**
         * Sets the value of the objFlags property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setObjFlags(byte[] value) {
            this.objFlags = ((byte[]) value);
        }

        /**
         * Gets the value of the uniqueIDRef property.
         * 
         * @return
         *     possible object is
         *     {@link java.lang.Object }
         *     
         */
        public java.lang.Object getUniqueIDRef() {
            return uniqueIDRef;
        }

        /**
         * Sets the value of the uniqueIDRef property.
         * 
         * @param value
         *     allowed object is
         *     {@link java.lang.Object }
         *     
         */
        public void setUniqueIDRef(java.lang.Object value) {
            this.uniqueIDRef = value;
        }

        /**
         * Gets the value of the subNumber property.
         * 
         * @return
         *     possible object is
         *     {@link Short }
         *     
         */
        public Short getSubNumber() {
            return subNumber;
        }

        /**
         * Sets the value of the subNumber property.
         * 
         * @param value
         *     allowed object is
         *     {@link Short }
         *     
         */
        public void setSubNumber(Short value) {
            this.subNumber = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;attribute name="subIndex" use="required" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
         *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="objectType" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" />
         *       &lt;attribute name="dataType" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
         *       &lt;attribute name="lowLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="highLimit" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="accessType">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *             &lt;enumeration value="ro"/>
         *             &lt;enumeration value="wo"/>
         *             &lt;enumeration value="rw"/>
         *             &lt;enumeration value="const"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="defaultValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="actualValue" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="denotation" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="PDOmapping">
         *         &lt;simpleType>
         *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
         *             &lt;enumeration value="no"/>
         *             &lt;enumeration value="default"/>
         *             &lt;enumeration value="optional"/>
         *             &lt;enumeration value="TPDO"/>
         *             &lt;enumeration value="RPDO"/>
         *             &lt;enumeration value="true"/>
         *             &lt;enumeration value="false"/>
         *           &lt;/restriction>
         *         &lt;/simpleType>
         *       &lt;/attribute>
         *       &lt;attribute name="objFlags" type="{http://www.w3.org/2001/XMLSchema}hexBinary" />
         *       &lt;attribute name="uniqueIDRef" type="{http://www.w3.org/2001/XMLSchema}IDREF" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "")
        public static class SubObject {

            @XmlAttribute(required = true)
            @XmlJavaTypeAdapter(HexBinaryAdapter.class)
            @XmlSchemaType(name = "hexBinary")
            protected byte[] subIndex;
            @XmlAttribute(required = true)
            protected String name;
            @XmlAttribute(required = true)
            @XmlSchemaType(name = "unsignedByte")
            protected short objectType;
            @XmlAttribute
            @XmlJavaTypeAdapter(HexBinaryAdapter.class)
            @XmlSchemaType(name = "hexBinary")
            protected byte[] dataType;
            @XmlAttribute
            protected String lowLimit;
            @XmlAttribute
            protected String highLimit;
            @XmlAttribute
            protected String accessType;
            @XmlAttribute
            protected String defaultValue;
            @XmlAttribute
            protected String actualValue;
            @XmlAttribute
            protected String denotation;
            @XmlAttribute(name = "PDOmapping")
            @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
            protected String pdOmapping;
            @XmlAttribute
            @XmlJavaTypeAdapter(HexBinaryAdapter.class)
            @XmlSchemaType(name = "hexBinary")
            protected byte[] objFlags;
            @XmlAttribute
            @XmlIDREF
            @XmlSchemaType(name = "IDREF")
            protected java.lang.Object uniqueIDRef;

            /**
             * Gets the value of the subIndex property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public byte[] getSubIndex() {
                return subIndex;
            }

            /**
             * Sets the value of the subIndex property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setSubIndex(byte[] value) {
                this.subIndex = ((byte[]) value);
            }

            /**
             * Gets the value of the name property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getName() {
                return name;
            }

            /**
             * Sets the value of the name property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setName(String value) {
                this.name = value;
            }

            /**
             * Gets the value of the objectType property.
             * 
             */
            public short getObjectType() {
                return objectType;
            }

            /**
             * Sets the value of the objectType property.
             * 
             */
            public void setObjectType(short value) {
                this.objectType = value;
            }

            /**
             * Gets the value of the dataType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public byte[] getDataType() {
                return dataType;
            }

            /**
             * Sets the value of the dataType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDataType(byte[] value) {
                this.dataType = ((byte[]) value);
            }

            /**
             * Gets the value of the lowLimit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLowLimit() {
                return lowLimit;
            }

            /**
             * Sets the value of the lowLimit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLowLimit(String value) {
                this.lowLimit = value;
            }

            /**
             * Gets the value of the highLimit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHighLimit() {
                return highLimit;
            }

            /**
             * Sets the value of the highLimit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHighLimit(String value) {
                this.highLimit = value;
            }

            /**
             * Gets the value of the accessType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAccessType() {
                return accessType;
            }

            /**
             * Sets the value of the accessType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAccessType(String value) {
                this.accessType = value;
            }

            /**
             * Gets the value of the defaultValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDefaultValue() {
                return defaultValue;
            }

            /**
             * Sets the value of the defaultValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDefaultValue(String value) {
                this.defaultValue = value;
            }

            /**
             * Gets the value of the actualValue property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getActualValue() {
                return actualValue;
            }

            /**
             * Sets the value of the actualValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setActualValue(String value) {
                this.actualValue = value;
            }

            /**
             * Gets the value of the denotation property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getDenotation() {
                return denotation;
            }

            /**
             * Sets the value of the denotation property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setDenotation(String value) {
                this.denotation = value;
            }

            /**
             * Gets the value of the pdOmapping property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPDOmapping() {
                return pdOmapping;
            }

            /**
             * Sets the value of the pdOmapping property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPDOmapping(String value) {
                this.pdOmapping = value;
            }

            /**
             * Gets the value of the objFlags property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public byte[] getObjFlags() {
                return objFlags;
            }

            /**
             * Sets the value of the objFlags property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setObjFlags(byte[] value) {
                this.objFlags = ((byte[]) value);
            }

            /**
             * Gets the value of the uniqueIDRef property.
             * 
             * @return
             *     possible object is
             *     {@link java.lang.Object }
             *     
             */
            public java.lang.Object getUniqueIDRef() {
                return uniqueIDRef;
            }

            /**
             * Sets the value of the uniqueIDRef property.
             * 
             * @param value
             *     allowed object is
             *     {@link java.lang.Object }
             *     
             */
            public void setUniqueIDRef(java.lang.Object value) {
                this.uniqueIDRef = value;
            }

        }

    }

}
