//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.ethernet_powerlink package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _BuildDate_QNAME = new QName("http://www.ethernet-powerlink.org", "buildDate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.ethernet_powerlink
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ActualValue }
     * 
     */
    public ActualValue createActualValue() {
        return new ActualValue();
    }

    /**
     * Create an instance of {@link CharacteristicsList.Category }
     * 
     */
    public CharacteristicsList.Category createCharacteristicsListCategory() {
        return new CharacteristicsList.Category();
    }

    /**
     * Create an instance of {@link ProductText }
     * 
     */
    public ProductText createProductText() {
        return new ProductText();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic createProfileBodyCommunicationNetworkPowerlinkNetworkManagementDiagnostic() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic();
    }

    /**
     * Create an instance of {@link CombinedState }
     * 
     */
    public CombinedState createCombinedState() {
        return new CombinedState();
    }

    /**
     * Create an instance of {@link FunctionInstanceList }
     * 
     */
    public FunctionInstanceList createFunctionInstanceList() {
        return new FunctionInstanceList();
    }

    /**
     * Create an instance of {@link ApplicationProcess }
     * 
     */
    public ApplicationProcess createApplicationProcess() {
        return new ApplicationProcess();
    }

    /**
     * Create an instance of {@link FunctionInstance }
     * 
     */
    public FunctionInstance createFunctionInstance() {
        return new FunctionInstance();
    }

    /**
     * Create an instance of {@link Derived }
     * 
     */
    public Derived createDerived() {
        return new Derived();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DataTypeList }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DataTypeList createProfileBodyCommunicationNetworkPowerlinkApplicationLayersDataTypeList() {
        return new ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DataTypeList();
    }

    /**
     * Create an instance of {@link ObjectList.Object.SubObject }
     * 
     */
    public ObjectList.Object.SubObject createObjectListObjectSubObject() {
        return new ObjectList.Object.SubObject();
    }

    /**
     * Create an instance of {@link Version }
     * 
     */
    public Version createVersion() {
        return new Version();
    }

    /**
     * Create an instance of {@link SubstituteValue }
     * 
     */
    public SubstituteValue createSubstituteValue() {
        return new SubstituteValue();
    }

    /**
     * Create an instance of {@link Count.Description }
     * 
     */
    public Count.Description createCountDescription() {
        return new Count.Description();
    }

    /**
     * Create an instance of {@link Property }
     * 
     */
    public Property createProperty() {
        return new Property();
    }

    /**
     * Create an instance of {@link OutputVars }
     * 
     */
    public OutputVars createOutputVars() {
        return new OutputVars();
    }

    /**
     * Create an instance of {@link TypeErrorBit }
     * 
     */
    public TypeErrorBit createTypeErrorBit() {
        return new TypeErrorBit();
    }

    /**
     * Create an instance of {@link VariableRef }
     * 
     */
    public VariableRef createVariableRef() {
        return new VariableRef();
    }

    /**
     * Create an instance of {@link OrderNumber }
     * 
     */
    public OrderNumber createOrderNumber() {
        return new OrderNumber();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink createProfileBodyCommunicationNetworkPowerlink() {
        return new ProfileBodyCommunicationNetworkPowerlink();
    }

    /**
     * Create an instance of {@link Denotation }
     * 
     */
    public Denotation createDenotation() {
        return new Denotation();
    }

    /**
     * Create an instance of {@link VersionInfo }
     * 
     */
    public VersionInfo createVersionInfo() {
        return new VersionInfo();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DataTypeList.DefType }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DataTypeList.DefType createProfileBodyCommunicationNetworkPowerlinkApplicationLayersDataTypeListDefType() {
        return new ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DataTypeList.DefType();
    }

    /**
     * Create an instance of {@link AllowedValues }
     * 
     */
    public AllowedValues createAllowedValues() {
        return new AllowedValues();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.MNFeatures }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.MNFeatures createProfileBodyCommunicationNetworkPowerlinkNetworkManagementMNFeatures() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.MNFeatures();
    }

    /**
     * Create an instance of {@link PicturesList }
     * 
     */
    public PicturesList createPicturesList() {
        return new PicturesList();
    }

    /**
     * Create an instance of {@link ISO15745Profile }
     * 
     */
    public ISO15745Profile createISO15745Profile() {
        return new ISO15745Profile();
    }

    /**
     * Create an instance of {@link InputVars }
     * 
     */
    public InputVars createInputVars() {
        return new InputVars();
    }

    /**
     * Create an instance of {@link Enum }
     * 
     */
    public Enum createEnum() {
        return new Enum();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DynamicChannels }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DynamicChannels createProfileBodyCommunicationNetworkPowerlinkApplicationLayersDynamicChannels() {
        return new ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DynamicChannels();
    }

    /**
     * Create an instance of {@link Picture }
     * 
     */
    public Picture createPicture() {
        return new Picture();
    }

    /**
     * Create an instance of {@link ProductName }
     * 
     */
    public ProductName createProductName() {
        return new ProductName();
    }

    /**
     * Create an instance of {@link LED }
     * 
     */
    public LED createLED() {
        return new LED();
    }

    /**
     * Create an instance of {@link org.ethernet_powerlink.Value }
     * 
     */
    public org.ethernet_powerlink.Value createValue() {
        return new org.ethernet_powerlink.Value();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.Identity }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.Identity createProfileBodyCommunicationNetworkPowerlinkApplicationLayersIdentity() {
        return new ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.Identity();
    }

    /**
     * Create an instance of {@link ParameterList }
     * 
     */
    public ParameterList createParameterList() {
        return new ParameterList();
    }

    /**
     * Create an instance of {@link Unit }
     * 
     */
    public Unit createUnit() {
        return new Unit();
    }

    /**
     * Create an instance of {@link TextResource.TextEntry }
     * 
     */
    public TextResource.TextEntry createTextResourceTextEntry() {
        return new TextResource.TextEntry();
    }

    /**
     * Create an instance of {@link VendorName }
     * 
     */
    public VendorName createVendorName() {
        return new VendorName();
    }

    /**
     * Create an instance of {@link Count }
     * 
     */
    public Count createCount() {
        return new Count();
    }

    /**
     * Create an instance of {@link Dictionary }
     * 
     */
    public Dictionary createDictionary() {
        return new Dictionary();
    }

    /**
     * Create an instance of {@link ConfigVars }
     * 
     */
    public ConfigVars createConfigVars() {
        return new ConfigVars();
    }

    /**
     * Create an instance of {@link Capabilities }
     * 
     */
    public Capabilities createCapabilities() {
        return new Capabilities();
    }

    /**
     * Create an instance of {@link ProductFamily }
     * 
     */
    public ProductFamily createProductFamily() {
        return new ProductFamily();
    }

    /**
     * Create an instance of {@link StandardComplianceList }
     * 
     */
    public StandardComplianceList createStandardComplianceList() {
        return new StandardComplianceList();
    }

    /**
     * Create an instance of {@link InstanceName }
     * 
     */
    public InstanceName createInstanceName() {
        return new InstanceName();
    }

    /**
     * Create an instance of {@link AllowedValuesTemplate }
     * 
     */
    public AllowedValuesTemplate createAllowedValuesTemplate() {
        return new AllowedValuesTemplate();
    }

    /**
     * Create an instance of {@link VariableIDRef }
     * 
     */
    public VariableIDRef createVariableIDRef() {
        return new VariableIDRef();
    }

    /**
     * Create an instance of {@link VendorID }
     * 
     */
    public VendorID createVendorID() {
        return new VendorID();
    }

    /**
     * Create an instance of {@link org.ethernet_powerlink.DataTypeList }
     * 
     */
    public org.ethernet_powerlink.DataTypeList createDataTypeList() {
        return new org.ethernet_powerlink.DataTypeList();
    }

    /**
     * Create an instance of {@link DictionaryList }
     * 
     */
    public DictionaryList createDictionaryList() {
        return new DictionaryList();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement createProfileBodyCommunicationNetworkPowerlinkNetworkManagement() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement();
    }

    /**
     * Create an instance of {@link DeviceFunction }
     * 
     */
    public DeviceFunction createDeviceFunction() {
        return new DeviceFunction();
    }

    /**
     * Create an instance of {@link Characteristic }
     * 
     */
    public Characteristic createCharacteristic() {
        return new Characteristic();
    }

    /**
     * Create an instance of {@link VarDeclaration }
     * 
     */
    public VarDeclaration createVarDeclaration() {
        return new VarDeclaration();
    }

    /**
     * Create an instance of {@link ProfileHandleDataType }
     * 
     */
    public ProfileHandleDataType createProfileHandleDataType() {
        return new ProfileHandleDataType();
    }

    /**
     * Create an instance of {@link ObjectList.Object }
     * 
     */
    public ObjectList.Object createObjectListObject() {
        return new ObjectList.Object();
    }

    /**
     * Create an instance of {@link IndicatorList }
     * 
     */
    public IndicatorList createIndicatorList() {
        return new IndicatorList();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.DeviceCommissioning }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.DeviceCommissioning createProfileBodyCommunicationNetworkPowerlinkNetworkManagementDeviceCommissioning() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.DeviceCommissioning();
    }

    /**
     * Create an instance of {@link InstanceIDRef }
     * 
     */
    public InstanceIDRef createInstanceIDRef() {
        return new InstanceIDRef();
    }

    /**
     * Create an instance of {@link FunctionType }
     * 
     */
    public FunctionType createFunctionType() {
        return new FunctionType();
    }

    /**
     * Create an instance of {@link CharacteristicsList }
     * 
     */
    public CharacteristicsList createCharacteristicsList() {
        return new CharacteristicsList();
    }

    /**
     * Create an instance of {@link ProductID }
     * 
     */
    public ProductID createProductID() {
        return new ProductID();
    }

    /**
     * Create an instance of {@link SpecificationRevision }
     * 
     */
    public SpecificationRevision createSpecificationRevision() {
        return new SpecificationRevision();
    }

    /**
     * Create an instance of {@link Range.Step }
     * 
     */
    public Range.Step createRangeStep() {
        return new Range.Step();
    }

    /**
     * Create an instance of {@link LEDstate }
     * 
     */
    public LEDstate createLEDstate() {
        return new LEDstate();
    }

    /**
     * Create an instance of {@link ParameterGroup }
     * 
     */
    public ParameterGroup createParameterGroup() {
        return new ParameterGroup();
    }

    /**
     * Create an instance of {@link CharacteristicName }
     * 
     */
    public CharacteristicName createCharacteristicName() {
        return new CharacteristicName();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers createProfileBodyCommunicationNetworkPowerlinkApplicationLayers() {
        return new ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers();
    }

    /**
     * Create an instance of {@link ISO15745ProfileContainer }
     * 
     */
    public ISO15745ProfileContainer createISO15745ProfileContainer() {
        return new ISO15745ProfileContainer();
    }

    /**
     * Create an instance of {@link TypeErrorConstant.AddInfo }
     * 
     */
    public TypeErrorConstant.AddInfo createTypeErrorConstantAddInfo() {
        return new TypeErrorConstant.AddInfo();
    }

    /**
     * Create an instance of {@link ParameterRef }
     * 
     */
    public ParameterRef createParameterRef() {
        return new ParameterRef();
    }

    /**
     * Create an instance of {@link Range.MinValue }
     * 
     */
    public Range.MinValue createRangeMinValue() {
        return new Range.MinValue();
    }

    /**
     * Create an instance of {@link CombinedState.LEDstateRef }
     * 
     */
    public CombinedState.LEDstateRef createCombinedStateLEDstateRef() {
        return new CombinedState.LEDstateRef();
    }

    /**
     * Create an instance of {@link TemplateList }
     * 
     */
    public TemplateList createTemplateList() {
        return new TemplateList();
    }

    /**
     * Create an instance of {@link DeviceFamily }
     * 
     */
    public DeviceFamily createDeviceFamily() {
        return new DeviceFamily();
    }

    /**
     * Create an instance of {@link MemberRef }
     * 
     */
    public MemberRef createMemberRef() {
        return new MemberRef();
    }

    /**
     * Create an instance of {@link DeviceIdentity }
     * 
     */
    public DeviceIdentity createDeviceIdentity() {
        return new DeviceIdentity();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic.StaticErrorBitField }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic.StaticErrorBitField createProfileBodyCommunicationNetworkPowerlinkNetworkManagementDiagnosticStaticErrorBitField() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic.StaticErrorBitField();
    }

    /**
     * Create an instance of {@link ProfileBodyDevicePowerlink }
     * 
     */
    public ProfileBodyDevicePowerlink createProfileBodyDevicePowerlink() {
        return new ProfileBodyDevicePowerlink();
    }

    /**
     * Create an instance of {@link Count.LabelRef }
     * 
     */
    public Count.LabelRef createCountLabelRef() {
        return new Count.LabelRef();
    }

    /**
     * Create an instance of {@link Array }
     * 
     */
    public Array createArray() {
        return new Array();
    }

    /**
     * Create an instance of {@link ConditionalSupport }
     * 
     */
    public ConditionalSupport createConditionalSupport() {
        return new ConditionalSupport();
    }

    /**
     * Create an instance of {@link DataTypeIDRef }
     * 
     */
    public DataTypeIDRef createDataTypeIDRef() {
        return new DataTypeIDRef();
    }

    /**
     * Create an instance of {@link TypeErrorConstant.AddInfo.Value }
     * 
     */
    public TypeErrorConstant.AddInfo.Value createTypeErrorConstantAddInfoValue() {
        return new TypeErrorConstant.AddInfo.Value();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DynamicChannels.DynamicChannel }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DynamicChannels.DynamicChannel createProfileBodyCommunicationNetworkPowerlinkApplicationLayersDynamicChannelsDynamicChannel() {
        return new ProfileBodyCommunicationNetworkPowerlink.ApplicationLayers.DynamicChannels.DynamicChannel();
    }

    /**
     * Create an instance of {@link Connection }
     * 
     */
    public Connection createConnection() {
        return new Connection();
    }

    /**
     * Create an instance of {@link Range }
     * 
     */
    public Range createRange() {
        return new Range();
    }

    /**
     * Create an instance of {@link VendorText }
     * 
     */
    public VendorText createVendorText() {
        return new VendorText();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.CNFeatures }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.CNFeatures createProfileBodyCommunicationNetworkPowerlinkNetworkManagementCNFeatures() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.CNFeatures();
    }

    /**
     * Create an instance of {@link LEDList }
     * 
     */
    public LEDList createLEDList() {
        return new LEDList();
    }

    /**
     * Create an instance of {@link InterfaceList }
     * 
     */
    public InterfaceList createInterfaceList() {
        return new InterfaceList();
    }

    /**
     * Create an instance of {@link Count.Label }
     * 
     */
    public Count.Label createCountLabel() {
        return new Count.Label();
    }

    /**
     * Create an instance of {@link ProfileHeaderDataType }
     * 
     */
    public ProfileHeaderDataType createProfileHeaderDataType() {
        return new ProfileHeaderDataType();
    }

    /**
     * Create an instance of {@link EnumValue }
     * 
     */
    public EnumValue createEnumValue() {
        return new EnumValue();
    }

    /**
     * Create an instance of {@link ParameterTemplate }
     * 
     */
    public ParameterTemplate createParameterTemplate() {
        return new ParameterTemplate();
    }

    /**
     * Create an instance of {@link TextResource }
     * 
     */
    public TextResource createTextResource() {
        return new TextResource();
    }

    /**
     * Create an instance of {@link ISO15745ReferenceDataType }
     * 
     */
    public ISO15745ReferenceDataType createISO15745ReferenceDataType() {
        return new ISO15745ReferenceDataType();
    }

    /**
     * Create an instance of {@link Range.MaxValue }
     * 
     */
    public Range.MaxValue createRangeMaxValue() {
        return new Range.MaxValue();
    }

    /**
     * Create an instance of {@link Count.DescriptionRef }
     * 
     */
    public Count.DescriptionRef createCountDescriptionRef() {
        return new Count.DescriptionRef();
    }

    /**
     * Create an instance of {@link Subrange }
     * 
     */
    public Subrange createSubrange() {
        return new Subrange();
    }

    /**
     * Create an instance of {@link TypeErrorConstant }
     * 
     */
    public TypeErrorConstant createTypeErrorConstant() {
        return new TypeErrorConstant();
    }

    /**
     * Create an instance of {@link CharacteristicContent }
     * 
     */
    public CharacteristicContent createCharacteristicContent() {
        return new CharacteristicContent();
    }

    /**
     * Create an instance of {@link DefaultValue }
     * 
     */
    public DefaultValue createDefaultValue() {
        return new DefaultValue();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.GeneralFeatures }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.GeneralFeatures createProfileBodyCommunicationNetworkPowerlinkNetworkManagementGeneralFeatures() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.GeneralFeatures();
    }

    /**
     * Create an instance of {@link ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic.ErrorList }
     * 
     */
    public ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic.ErrorList createProfileBodyCommunicationNetworkPowerlinkNetworkManagementDiagnosticErrorList() {
        return new ProfileBodyCommunicationNetworkPowerlink.NetworkManagement.Diagnostic.ErrorList();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link CompliantWith }
     * 
     */
    public CompliantWith createCompliantWith() {
        return new CompliantWith();
    }

    /**
     * Create an instance of {@link DeviceManager }
     * 
     */
    public DeviceManager createDeviceManager() {
        return new DeviceManager();
    }

    /**
     * Create an instance of {@link Struct }
     * 
     */
    public Struct createStruct() {
        return new Struct();
    }

    /**
     * Create an instance of {@link FunctionTypeList }
     * 
     */
    public FunctionTypeList createFunctionTypeList() {
        return new FunctionTypeList();
    }

    /**
     * Create an instance of {@link ObjectList }
     * 
     */
    public ObjectList createObjectList() {
        return new ObjectList();
    }

    /**
     * Create an instance of {@link ParameterGroupList }
     * 
     */
    public ParameterGroupList createParameterGroupList() {
        return new ParameterGroupList();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ethernet-powerlink.org", name = "buildDate")
    public JAXBElement<XMLGregorianCalendar> createBuildDate(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_BuildDate_QNAME, XMLGregorianCalendar.class, null, value);
    }

}
