//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ProfileBody_Device_Powerlink complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProfileBody_Device_Powerlink">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ethernet-powerlink.org}ProfileBody_DataType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}DeviceIdentity" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}DeviceManager" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}DeviceFunction" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}ApplicationProcess" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExternalProfileHandle" type="{http://www.ethernet-powerlink.org}ProfileHandle_DataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attGroup ref="{http://www.ethernet-powerlink.org}ag_formatAndFile"/>
 *       &lt;attribute name="supportedLanguages" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" />
 *       &lt;attribute name="deviceClass">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="compact"/>
 *             &lt;enumeration value="modular"/>
 *             &lt;enumeration value="configurable"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProfileBody_Device_Powerlink", propOrder = {
    "deviceIdentity",
    "deviceManager",
    "deviceFunction",
    "applicationProcess",
    "externalProfileHandle"
})
public class ProfileBodyDevicePowerlink
    extends ProfileBodyDataType
{

    @XmlElement(name = "DeviceIdentity")
    protected DeviceIdentity deviceIdentity;
    @XmlElement(name = "DeviceManager")
    protected DeviceManager deviceManager;
    @XmlElement(name = "DeviceFunction", required = true)
    protected List<DeviceFunction> deviceFunction;
    @XmlElement(name = "ApplicationProcess")
    protected List<ApplicationProcess> applicationProcess;
    @XmlElement(name = "ExternalProfileHandle")
    protected List<ProfileHandleDataType> externalProfileHandle;
    @XmlAttribute
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> supportedLanguages;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String deviceClass;
    @XmlAttribute
    protected String formatName;
    @XmlAttribute
    protected String formatVersion;
    @XmlAttribute(required = true)
    protected String fileName;
    @XmlAttribute(required = true)
    protected String fileCreator;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fileCreationDate;
    @XmlAttribute
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar fileCreationTime;
    @XmlAttribute
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fileModificationDate;
    @XmlAttribute
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar fileModificationTime;
    @XmlAttribute
    protected String fileModifiedBy;
    @XmlAttribute(required = true)
    protected String fileVersion;

    /**
     * Gets the value of the deviceIdentity property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceIdentity }
     *     
     */
    public DeviceIdentity getDeviceIdentity() {
        return deviceIdentity;
    }

    /**
     * Sets the value of the deviceIdentity property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceIdentity }
     *     
     */
    public void setDeviceIdentity(DeviceIdentity value) {
        this.deviceIdentity = value;
    }

    /**
     * Gets the value of the deviceManager property.
     * 
     * @return
     *     possible object is
     *     {@link DeviceManager }
     *     
     */
    public DeviceManager getDeviceManager() {
        return deviceManager;
    }

    /**
     * Sets the value of the deviceManager property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeviceManager }
     *     
     */
    public void setDeviceManager(DeviceManager value) {
        this.deviceManager = value;
    }

    /**
     * Gets the value of the deviceFunction property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deviceFunction property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviceFunction().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeviceFunction }
     * 
     * 
     */
    public List<DeviceFunction> getDeviceFunction() {
        if (deviceFunction == null) {
            deviceFunction = new ArrayList<DeviceFunction>();
        }
        return this.deviceFunction;
    }

    /**
     * Gets the value of the applicationProcess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the applicationProcess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getApplicationProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ApplicationProcess }
     * 
     * 
     */
    public List<ApplicationProcess> getApplicationProcess() {
        if (applicationProcess == null) {
            applicationProcess = new ArrayList<ApplicationProcess>();
        }
        return this.applicationProcess;
    }

    /**
     * Gets the value of the externalProfileHandle property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the externalProfileHandle property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExternalProfileHandle().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProfileHandleDataType }
     * 
     * 
     */
    public List<ProfileHandleDataType> getExternalProfileHandle() {
        if (externalProfileHandle == null) {
            externalProfileHandle = new ArrayList<ProfileHandleDataType>();
        }
        return this.externalProfileHandle;
    }

    /**
     * Gets the value of the supportedLanguages property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the supportedLanguages property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSupportedLanguages().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSupportedLanguages() {
        if (supportedLanguages == null) {
            supportedLanguages = new ArrayList<String>();
        }
        return this.supportedLanguages;
    }

    /**
     * Gets the value of the deviceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceClass() {
        return deviceClass;
    }

    /**
     * Sets the value of the deviceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceClass(String value) {
        this.deviceClass = value;
    }

    /**
     * Gets the value of the formatName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatName() {
        if (formatName == null) {
            return "DDXML";
        } else {
            return formatName;
        }
    }

    /**
     * Sets the value of the formatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatName(String value) {
        this.formatName = value;
    }

    /**
     * Gets the value of the formatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormatVersion() {
        if (formatVersion == null) {
            return "2.0";
        } else {
            return formatVersion;
        }
    }

    /**
     * Sets the value of the formatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormatVersion(String value) {
        this.formatVersion = value;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the fileCreator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileCreator() {
        return fileCreator;
    }

    /**
     * Sets the value of the fileCreator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileCreator(String value) {
        this.fileCreator = value;
    }

    /**
     * Gets the value of the fileCreationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileCreationDate() {
        return fileCreationDate;
    }

    /**
     * Sets the value of the fileCreationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileCreationDate(XMLGregorianCalendar value) {
        this.fileCreationDate = value;
    }

    /**
     * Gets the value of the fileCreationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileCreationTime() {
        return fileCreationTime;
    }

    /**
     * Sets the value of the fileCreationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileCreationTime(XMLGregorianCalendar value) {
        this.fileCreationTime = value;
    }

    /**
     * Gets the value of the fileModificationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileModificationDate() {
        return fileModificationDate;
    }

    /**
     * Sets the value of the fileModificationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileModificationDate(XMLGregorianCalendar value) {
        this.fileModificationDate = value;
    }

    /**
     * Gets the value of the fileModificationTime property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFileModificationTime() {
        return fileModificationTime;
    }

    /**
     * Sets the value of the fileModificationTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFileModificationTime(XMLGregorianCalendar value) {
        this.fileModificationTime = value;
    }

    /**
     * Gets the value of the fileModifiedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileModifiedBy() {
        return fileModifiedBy;
    }

    /**
     * Sets the value of the fileModifiedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileModifiedBy(String value) {
        this.fileModifiedBy = value;
    }

    /**
     * Gets the value of the fileVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileVersion() {
        return fileVersion;
    }

    /**
     * Sets the value of the fileVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileVersion(String value) {
        this.fileVersion = value;
    }

}
