//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}parameterTemplate" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}allowedValuesTemplate" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "parameterTemplate",
    "allowedValuesTemplate"
})
@XmlRootElement(name = "templateList")
public class TemplateList {

    protected List<ParameterTemplate> parameterTemplate;
    protected List<AllowedValuesTemplate> allowedValuesTemplate;

    /**
     * Gets the value of the parameterTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameterTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameterTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterTemplate }
     * 
     * 
     */
    public List<ParameterTemplate> getParameterTemplate() {
        if (parameterTemplate == null) {
            parameterTemplate = new ArrayList<ParameterTemplate>();
        }
        return this.parameterTemplate;
    }

    /**
     * Gets the value of the allowedValuesTemplate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the allowedValuesTemplate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAllowedValuesTemplate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AllowedValuesTemplate }
     * 
     * 
     */
    public List<AllowedValuesTemplate> getAllowedValuesTemplate() {
        if (allowedValuesTemplate == null) {
            allowedValuesTemplate = new ArrayList<AllowedValuesTemplate>();
        }
        return this.allowedValuesTemplate;
    }

}
