//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TypeErrorBit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TypeErrorBit">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;group ref="{http://www.ethernet-powerlink.org}g_labels" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="offset" use="required" type="{http://www.ethernet-powerlink.org}TypeErrorBitOffset" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TypeErrorBit", propOrder = {
    "gLabels"
})
public class TypeErrorBit {

    @XmlElements({
        @XmlElement(name = "description", type = org.ethernet_powerlink.Count.Description.class),
        @XmlElement(name = "labelRef", type = org.ethernet_powerlink.Count.LabelRef.class),
        @XmlElement(name = "label", type = org.ethernet_powerlink.Count.Label.class),
        @XmlElement(name = "descriptionRef", type = org.ethernet_powerlink.Count.DescriptionRef.class)
    })
    protected List<Object> gLabels;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute(required = true)
    protected int offset;

    /**
     * Gets the value of the gLabels property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gLabels property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGLabels().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link org.ethernet_powerlink.Count.Description }
     * {@link org.ethernet_powerlink.Count.LabelRef }
     * {@link org.ethernet_powerlink.Count.Label }
     * {@link org.ethernet_powerlink.Count.DescriptionRef }
     * 
     * 
     */
    public List<Object> getGLabels() {
        if (gLabels == null) {
            gLabels = new ArrayList<Object>();
        }
        return this.gLabels;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the offset property.
     * 
     */
    public int getOffset() {
        return offset;
    }

    /**
     * Sets the value of the offset property.
     * 
     */
    public void setOffset(int value) {
        this.offset = value;
    }

}
