//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.30 at 07:55:07 PM CEST 
//


package org.ethernet_powerlink;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}instanceIDRef" maxOccurs="unbounded"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}variableIDRef"/>
 *         &lt;element ref="{http://www.ethernet-powerlink.org}memberRef" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="position" type="{http://www.w3.org/2001/XMLSchema}unsignedByte" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "instanceIDRef",
    "variableIDRef",
    "memberRef"
})
@XmlRootElement(name = "variableRef")
public class VariableRef {

    @XmlElement(required = true)
    protected List<InstanceIDRef> instanceIDRef;
    @XmlElement(required = true)
    protected VariableIDRef variableIDRef;
    protected List<MemberRef> memberRef;
    @XmlAttribute
    @XmlSchemaType(name = "unsignedByte")
    protected Short position;

    /**
     * Gets the value of the instanceIDRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the instanceIDRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInstanceIDRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InstanceIDRef }
     * 
     * 
     */
    public List<InstanceIDRef> getInstanceIDRef() {
        if (instanceIDRef == null) {
            instanceIDRef = new ArrayList<InstanceIDRef>();
        }
        return this.instanceIDRef;
    }

    /**
     * Gets the value of the variableIDRef property.
     * 
     * @return
     *     possible object is
     *     {@link VariableIDRef }
     *     
     */
    public VariableIDRef getVariableIDRef() {
        return variableIDRef;
    }

    /**
     * Sets the value of the variableIDRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link VariableIDRef }
     *     
     */
    public void setVariableIDRef(VariableIDRef value) {
        this.variableIDRef = value;
    }

    /**
     * Gets the value of the memberRef property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the memberRef property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMemberRef().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MemberRef }
     * 
     * 
     */
    public List<MemberRef> getMemberRef() {
        if (memberRef == null) {
            memberRef = new ArrayList<MemberRef>();
        }
        return this.memberRef;
    }

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link Short }
     *     
     */
    public short getPosition() {
        if (position == null) {
            return ((short) 1);
        } else {
            return position;
        }
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link Short }
     *     
     */
    public void setPosition(Short value) {
        this.position = value;
    }

}
