//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.04 at 06:51:08 PM CET 
//


package cz.rexcontrols.epl.editor.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}Number"/>
 *         &lt;element ref="{}RexNode"/>
 *         &lt;element ref="{}SourceFile"/>
 *         &lt;element ref="{}CfgIndexes"/>
 *         &lt;element ref="{}Disabled" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "number",
    "rexNode",
    "sourceFile",
    "cfgIndexes",
    "disabled"
})
@XmlRootElement(name = "CfgNode")
public class CfgNode {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "Number")
    protected int number;
    @XmlElement(name = "RexNode")
    protected boolean rexNode;
    @XmlElement(name = "SourceFile", required = true)
    protected String sourceFile;
    @XmlElement(name = "CfgIndexes", required = true)
    protected CfgIndexes cfgIndexes;
    @XmlElement(name = "Disabled")
    protected Boolean disabled;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the number property.
     * 
     */
    public int getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     */
    public void setNumber(int value) {
        this.number = value;
    }

    /**
     * Gets the value of the rexNode property.
     * 
     */
    public boolean isRexNode() {
        return rexNode;
    }

    /**
     * Sets the value of the rexNode property.
     * 
     */
    public void setRexNode(boolean value) {
        this.rexNode = value;
    }

    /**
     * Gets the value of the sourceFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceFile() {
        return sourceFile;
    }

    /**
     * Sets the value of the sourceFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceFile(String value) {
        this.sourceFile = value;
    }

    /**
     * Gets the value of the cfgIndexes property.
     * 
     * @return
     *     possible object is
     *     {@link CfgIndexes }
     *     
     */
    public CfgIndexes getCfgIndexes() {
        return cfgIndexes;
    }

    /**
     * Sets the value of the cfgIndexes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CfgIndexes }
     *     
     */
    public void setCfgIndexes(CfgIndexes value) {
        this.cfgIndexes = value;
    }

    /**
     * Gets the value of the disabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isDisabled() {
        return disabled;
    }

    /**
     * Sets the value of the disabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDisabled(Boolean value) {
        this.disabled = value;
    }

}
