//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.04 at 06:51:08 PM CET 
//


package cz.rexcontrols.epl.editor.project;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Name"/>
 *         &lt;element ref="{}CycleLength"/>
 *         &lt;element ref="{}AdvancedView"/>
 *         &lt;element ref="{}CfgNodes"/>
 *         &lt;element ref="{}CfgConnections"/>
 *         &lt;element ref="{}ConfigurationTime"/>
 *         &lt;element ref="{}ConfigurationDate"/>
 *         &lt;element ref="{}CfgAliases"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "name",
    "cycleLength",
    "advancedView",
    "cfgNodes",
    "cfgConnections",
    "configurationTime",
    "configurationDate",
    "cfgAliases"
})
@XmlRootElement(name = "CfgProject")
public class CfgProject {

    @XmlElement(name = "Name", required = true)
    protected String name;
    @XmlElement(name = "CycleLength")
    protected int cycleLength;
    @XmlElement(name = "AdvancedView")
    protected boolean advancedView;
    @XmlElement(name = "CfgNodes", required = true)
    protected CfgNodes cfgNodes;
    @XmlElement(name = "CfgConnections", required = true)
    protected CfgConnections cfgConnections;
    @XmlElement(name = "ConfigurationTime")
    protected long configurationTime;
    @XmlElement(name = "ConfigurationDate")
    protected long configurationDate;
    @XmlElement(name = "CfgAliases", required = true)
    protected CfgAliases cfgAliases;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the cycleLength property.
     * 
     */
    public int getCycleLength() {
        return cycleLength;
    }

    /**
     * Sets the value of the cycleLength property.
     * 
     */
    public void setCycleLength(int value) {
        this.cycleLength = value;
    }

    /**
     * Gets the value of the advancedView property.
     * 
     */
    public boolean isAdvancedView() {
        return advancedView;
    }

    /**
     * Sets the value of the advancedView property.
     * 
     */
    public void setAdvancedView(boolean value) {
        this.advancedView = value;
    }

    /**
     * Gets the value of the cfgNodes property.
     * 
     * @return
     *     possible object is
     *     {@link CfgNodes }
     *     
     */
    public CfgNodes getCfgNodes() {
        return cfgNodes;
    }

    /**
     * Sets the value of the cfgNodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CfgNodes }
     *     
     */
    public void setCfgNodes(CfgNodes value) {
        this.cfgNodes = value;
    }

    /**
     * Gets the value of the cfgConnections property.
     * 
     * @return
     *     possible object is
     *     {@link CfgConnections }
     *     
     */
    public CfgConnections getCfgConnections() {
        return cfgConnections;
    }

    /**
     * Sets the value of the cfgConnections property.
     * 
     * @param value
     *     allowed object is
     *     {@link CfgConnections }
     *     
     */
    public void setCfgConnections(CfgConnections value) {
        this.cfgConnections = value;
    }

    /**
     * Gets the value of the configurationTime property.
     * 
     */
    public long getConfigurationTime() {
        return configurationTime;
    }

    /**
     * Sets the value of the configurationTime property.
     * 
     */
    public void setConfigurationTime(long value) {
        this.configurationTime = value;
    }

    /**
     * Gets the value of the configurationDate property.
     * 
     */
    public long getConfigurationDate() {
        return configurationDate;
    }

    /**
     * Sets the value of the configurationDate property.
     * 
     */
    public void setConfigurationDate(long value) {
        this.configurationDate = value;
    }

    /**
     * Gets the value of the cfgAliases property.
     * 
     * @return
     *     possible object is
     *     {@link CfgAliases }
     *     
     */
    public CfgAliases getCfgAliases() {
        return cfgAliases;
    }

    /**
     * Sets the value of the cfgAliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link CfgAliases }
     *     
     */
    public void setCfgAliases(CfgAliases value) {
        this.cfgAliases = value;
    }

}
