//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.11.04 at 06:51:08 PM CET 
//


package cz.rexcontrols.epl.editor.project;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cz.rexcontrols.epl.editor.project package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RexNode_QNAME = new QName("", "RexNode");
    private final static QName _Number_QNAME = new QName("", "Number");
    private final static QName _CycleLength_QNAME = new QName("", "CycleLength");
    private final static QName _SourceFile_QNAME = new QName("", "SourceFile");
    private final static QName _ConfigurationTime_QNAME = new QName("", "ConfigurationTime");
    private final static QName _Name_QNAME = new QName("", "Name");
    private final static QName _ConfigurationDate_QNAME = new QName("", "ConfigurationDate");
    private final static QName _CdcExportable_QNAME = new QName("", "CdcExportable");
    private final static QName _AdvancedView_QNAME = new QName("", "AdvancedView");
    private final static QName _Disabled_QNAME = new QName("", "Disabled");
    private final static QName _IsRex_QNAME = new QName("", "IsRex");
    private final static QName _UserObject_QNAME = new QName("", "UserObject");
    private final static QName _Label_QNAME = new QName("", "Label");
    private final static QName _Destination_QNAME = new QName("", "Destination");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cz.rexcontrols.epl.editor.project
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CfgConnection }
     * 
     */
    public CfgConnection createCfgConnection() {
        return new CfgConnection();
    }

    /**
     * Create an instance of {@link CfgSubindexes }
     * 
     */
    public CfgSubindexes createCfgSubindexes() {
        return new CfgSubindexes();
    }

    /**
     * Create an instance of {@link CfgNode }
     * 
     */
    public CfgNode createCfgNode() {
        return new CfgNode();
    }

    /**
     * Create an instance of {@link CfgAliases }
     * 
     */
    public CfgAliases createCfgAliases() {
        return new CfgAliases();
    }

    /**
     * Create an instance of {@link CfgIndexes }
     * 
     */
    public CfgIndexes createCfgIndexes() {
        return new CfgIndexes();
    }

    /**
     * Create an instance of {@link CfgNodes }
     * 
     */
    public CfgNodes createCfgNodes() {
        return new CfgNodes();
    }

    /**
     * Create an instance of {@link CfgAlias }
     * 
     */
    public CfgAlias createCfgAlias() {
        return new CfgAlias();
    }

    /**
     * Create an instance of {@link CfgSubindex }
     * 
     */
    public CfgSubindex createCfgSubindex() {
        return new CfgSubindex();
    }

    /**
     * Create an instance of {@link CfgConnections }
     * 
     */
    public CfgConnections createCfgConnections() {
        return new CfgConnections();
    }

    /**
     * Create an instance of {@link CfgIndex }
     * 
     */
    public CfgIndex createCfgIndex() {
        return new CfgIndex();
    }

    /**
     * Create an instance of {@link CfgDataIdent }
     * 
     */
    public CfgDataIdent createCfgDataIdent() {
        return new CfgDataIdent();
    }

    /**
     * Create an instance of {@link CfgProject }
     * 
     */
    public CfgProject createCfgProject() {
        return new CfgProject();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "RexNode")
    public JAXBElement<Boolean> createRexNode(Boolean value) {
        return new JAXBElement<Boolean>(_RexNode_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Number")
    public JAXBElement<Integer> createNumber(Integer value) {
        return new JAXBElement<Integer>(_Number_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CycleLength")
    public JAXBElement<Integer> createCycleLength(Integer value) {
        return new JAXBElement<Integer>(_CycleLength_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SourceFile")
    public JAXBElement<String> createSourceFile(String value) {
        return new JAXBElement<String>(_SourceFile_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConfigurationTime")
    public JAXBElement<Long> createConfigurationTime(Long value) {
        return new JAXBElement<Long>(_ConfigurationTime_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Name")
    public JAXBElement<String> createName(String value) {
        return new JAXBElement<String>(_Name_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ConfigurationDate")
    public JAXBElement<Long> createConfigurationDate(Long value) {
        return new JAXBElement<Long>(_ConfigurationDate_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CdcExportable")
    public JAXBElement<Boolean> createCdcExportable(Boolean value) {
        return new JAXBElement<Boolean>(_CdcExportable_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "AdvancedView")
    public JAXBElement<Boolean> createAdvancedView(Boolean value) {
        return new JAXBElement<Boolean>(_AdvancedView_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Disabled")
    public JAXBElement<Boolean> createDisabled(Boolean value) {
        return new JAXBElement<Boolean>(_Disabled_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "IsRex")
    public JAXBElement<Boolean> createIsRex(Boolean value) {
        return new JAXBElement<Boolean>(_IsRex_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UserObject")
    public JAXBElement<Boolean> createUserObject(Boolean value) {
        return new JAXBElement<Boolean>(_UserObject_QNAME, Boolean.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Label")
    public JAXBElement<String> createLabel(String value) {
        return new JAXBElement<String>(_Label_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CfgDataIdent }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Destination")
    public JAXBElement<CfgDataIdent> createDestination(CfgDataIdent value) {
        return new JAXBElement<CfgDataIdent>(_Destination_QNAME, CfgDataIdent.class, null, value);
    }

}
